### ISSUE TITLE
cardano-db-sync workaround

### ISSUE THREAD

**Issue by hududed** [woofpool/cardano-private-testnet-setup#13]
Following up on the cardano-db-sync [workaround](https://github.com/woofpool/cardano-private-testnet-setup/issues/5#issuecomment-1036554078)

Running `cabal build all` results in:
```
create a better error message. Original error message:                                                                                                                                                      
Could not resolve dependencies:                                                                                                                                                                             
[__0] trying: Win32-network-0.1.0.0 (user goal)                                                                                                                                                             
[__1] trying: base-4.14.3.0/installed-4.14.3.0 (dependency of Win32-network)                                                                                                                                
[__2] trying: byron-spec-chain-0.1.0.0 (user goal)                                                                                                                                                          
[__3] trying: microlens-th-0.4.3.10 (dependency of byron-spec-chain)                                                                                                                                        
[__4] trying: template-haskell-2.16.0.0/installed-2.16.0.0 (dependency of                                                                                                                                   
microlens-th)                                                                                                                                                                                               
[__5] trying: pretty-1.1.3.6/installed-1.1.3.6 (dependency of                                                                                                                                               
template-haskell)                                                                                                                                                                                           
[__6] trying: hedgehog-1.0.5 (dependency of byron-spec-chain)                                                                                                                                               
[__7] trying: time-1.9.3/installed-1.9.3 (dependency of hedgehog)                                                                                                                                           
[__8] trying: text-1.2.4.1/installed-1.2.4.1 (dependency of hedgehog)                                                                                                                                       
[__9] trying: cardano-api-1.31.0 (user goal)
[_10] trying: scientific-0.3.7.0 (dependency of cardano-api)
[_11] trying: aeson-1.5.6.0 (dependency of cardano-api)
[_12] trying: cardano-db-12.0.2 (user goal)
[_13] trying: postgresql-simple-0.6.4 (dependency of cardano-db)
[_14] trying: postgresql-libpq-0.9.4.3 (dependency of postgresql-simple)
[_15] rejecting: postgresql-libpq:-use-pkg-config (constraint from config
file, command line flag, or user target requires opposite flag selection)
[_15] rejecting: postgresql-libpq:+use-pkg-config (conflict: pkg-config
package libpq>=9.3, not found in the pkg-config database)
[_15] fail (backjumping, conflict set: postgresql-libpq,
postgresql-libpq:use-pkg-config)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: postgresql-simple, base,
postgresql-libpq, aeson, text, time, postgresql-libpq:use-pkg-config,
scientific, cardano-db, cardano-api, hedgehog, pretty, template-haskell,
byron-spec-chain, microlens-th, Win32-network
```
Did you use cabal? Or something else like [nix-build](https://cardano.stackexchange.com/questions/3766/cardano-db-sync-build-instructions)?

**Comment by woofpool** [comment]
I did not build inside of a nix-shell, but this would probably be smart to save hassle of building all the dependencies.

```
# change directory to root of the cardano-db-sync project
cabal update
cabal build all
```

**Comment by woofpool** [comment]
Hi @hududed , hope all is well.  I just realized that I had forgot to include some important script changes to the main branch, so that attaching `cardano-db-sync` will work with the executable that includes the cherry-pick commits.  I just created the PR now, so it should get merged soon. https://github.com/woofpool/cardano-private-testnet-setup/pull/15/files
Sorry about that.

**Comment by hududed** [comment]
No worries - I will engage again once PR is merged

**Comment by grzegorznowak** [comment]
that's merged now, and doesn't seem to be affecting the devnet tests' passing. Which is great, though I must admit those changes don't tell me much (yet). Good stuff @woofpool .

You should be good to carry on @hududed 👍🏾

**Comment by hududed** [comment]
So I had a fresh clone of `cardano-private-testnet-setup` and `cardano-db-sync`, and used the cherry-pick commits as given in the workaround. Ran `cabal update` and `cabal build all` and still got the same error above - not exactly sure what's wrong

Added [issue](https://github.com/input-output-hk/cardano-db-sync/issues/1063) at `cardano-db-sync`

**Comment by hududed** [comment]
ok I was missing `sudo apt install pkg-config libpq-dev` - now `cabal build all` works.

But how do I run `cardano-db-sync`? I created the postgres database and ran:
```
ROOT=private-testnet
./scripts/db-sync-start.sh
```
got the error:
```
./scripts/db-sync-start.sh: line 17: cardano-db-sync: command not found
```

**Comment by woofpool** [comment]
> ok I was missing `sudo apt install pkg-config libpq-dev` - now `cabal build all` works.
>
Glad you got past the build issues.
 
> But how do I run `cardano-db-sync`? I created the postgres database and ran:
> 
> ```
> ROOT=private-testnet
> ./scripts/db-sync-start.sh
> ```
> 
> got the error:
> 
> ```
> ./scripts/db-sync-start.sh: line 17: cardano-db-sync: command not found
> ```
It looks like you don't have `cardano-db-sync` executable in your system path.  Did you copy the executable to some location on your path, e.g. `$HOME/.local/bin`?

**Comment by hududed** [comment]
Ahhh my bad. Didn't know where it was so I ran `find . -name cardano-db-sync -executable -type f` and copied that output into `~/.local/bin`, updated `SCHEMA_DIR` and now its ok!
Many thanks

**Comment by woofpool** [comment]
Awesome!
