### ISSUE TITLE
Possible to use Ogmios and create a custom database instead of using Postgres?

### ISSUE THREAD

**Issue by Et9797** [woofpool/cardano-private-testnet-setup#22]
Does Ogmios chain sync work with the private test net?

**Comment by extramileit** [comment]
I bet it is. I just skimmed [Ogmios getting started](https://ogmios.dev/getting-started/docker/) and they show a way to run ogmios in docker container by pointing at your node socket and node config.  

- Here is the [link to example](https://ogmios.dev/getting-started/docker/#running-bare-hands).  
     - In the example parameters for `node-config`, you could supply the `/path/to/private-testnet/configuration.yaml` instead of the `config.json`.  I believe they are interchangeable.

I also notice that the [cardano graph-ql project](https://github.com/input-output-hk/cardano-graphql) uses Ogmios bridge and cardano-db-sync as the backend data source.
In my opinion, using graphql would be ideal, b/c it abstracts away using SQL that is specific to the database.  

- I see an [issue](https://github.com/input-output-hk/cardano-graphql/issues/711) is logged in the cardano-graphql repo, which describes running against a private testnet.

If you have time to investigate getting Ogmios or GraphQl running against a private testnet, that would make for some great documentation to add to this guide!

**Comment by Et9797** [comment]
Works great. For those interested:

```
docker run --rm \
  --name ogmios \
  -p 1337:1337 \
  -v ${PWD}/private-testnet:/testnet \
  cardanosolutions/ogmios:latest \
    --node-socket /testnet/node-bft1/node.sock \
    --node-config /testnet/configuration.yaml \
    --host 0.0.0.0
```

**Comment by grzegorznowak** [comment]
well played on ^ guys 👏🏾 

A few additional words from the SecOps land here now for future us.
Always be extremely wary when using someone else's images directly, especially if `:latest` tag is used, and ever more so especially when things like real ledger is involved. 

I'm well aware we're talking testnets here only, but a caution to anyone who's going to arrive here later to copy pasta this into their very much actual project is due:

### Please make sure you understand and trust the containers you use, and make sure to checksum-target images used even if you do

ie.
`cardanosolutions/ogmios:latest` -> `cardanosolutions/ogmios@sha256:7a34a2abceadf66853d028c5099881c49df64907beba518fcc61e772fd4dbe46`

which might be harder to work with - especially with rolling updates - but is a must for critical applications.

Cheers.

**Comment by extramileit** [comment]
Excellent advice, @grzegorznowak!  I have been using `latest` tags on some other projects, and you made me realize I need to be more careful.

**Comment by Et9797** [comment]
One addition, it seems that other ports than 1337 do not work. I raised this issue on the official Ogmios github: https://github.com/CardanoSolutions/ogmios/issues/221.
Here's a minimal working example in Typescript to connect to the Ogmios container

```
import { createInteractionContext,  } from '@cardano-ogmios/client';
import { InteractionContext } from '@cardano-ogmios/client';

const config = {
    connection: {
        host: 'localhost',
        port: 1337,
        tls: false
    }
}

const context: InteractionContext = await createInteractionContext(
    err => console.error(err),
    () => console.log("Connection closed."),
    { connection: config.connection }
)
console.log(context)

```
Should be able to create the InteractionContext for the private testnet now (and use other libraries compatible with Ogmios, eg Pycardano, to build and submit transactions)

**Comment by KtorZ** [comment]
Small-note: Ogmios should fully work with any Cardano network so long as the network runs a version of _Cardano_. That is, a combination of all the existing eras (Byron; Shelley; Allegra; Mary; Alonzo; Babbage...). In principle, you can create a private cluster of nodes that only run one of those eras, or a subset of them. This won't however work with Ogmios.
