### ISSUE TITLE
node config errors

### ISSUE THREAD

**Issue by hududed** [woofpool/cardano-private-testnet-setup#5]
Up to step number 4 I got the following error:

```
hud@hud:~/src/cardano-private-testnet-setup$ ./scripts/db-sync-start.sh
[db-sync-node:Info:6] [2022-02-02 00:27:17.80 UTC] Schema migration files validated
[db-sync-node:Info:6] [2022-02-02 00:27:17.80 UTC] Running database migrations
[db-sync-node:Info:6] [2022-02-02 00:27:17.80 UTC] Enviroment variable DbSyncAbortOnPanic: False
ExitFailure 2

Errors in file: /tmp/migrate-2022-02-02T002717.log

hud@hud:~/src/cardano-private-testnet-setup$ cat /tmp/migrate-2022-02-02T002717.log
Running : migration-1-0000-20190730.sql
WARNING: password file "postgres-conn/pgpass-privatenet" has group or world access; permissions should be u=rw (0600) or less
psql: FATAL:  database "privatenet" does not exist
ExitFailure 2
```

After running the possibly missing instructions `sudo chmod 700 -R postgres-conn/pgpass-privatenet` and `createdb privatenet` I get the following errors:
```
hud@hud-PS63:~/src/cardano-private-testnet-setup$ ./scripts/db-sync-start.sh
[db-sync-node:Info:6] [2022-02-02 13:49:06.98 UTC] Schema migration files validated
[db-sync-node:Info:6] [2022-02-02 13:49:06.98 UTC] Running database migrations
[db-sync-node:Info:6] [2022-02-02 13:49:06.98 UTC] Enviroment variable DbSyncAbortOnPanic: False
[db-sync-node:Info:6] [2022-02-02 13:49:09.36 UTC] Using byron genesis file from: "private-testnet/./byron/genesis.json"
[db-sync-node:Info:6] [2022-02-02 13:49:09.36 UTC] Using shelley genesis file from: "private-testnet/./shelley/genesis.json"
[db-sync-node:Info:6] [2022-02-02 13:49:09.36 UTC] Using alonzo genesis file from: "private-testnet/./shelley/genesis.alonzo.json"
[db-sync-node:Info:6] [2022-02-02 13:49:09.36 UTC] NetworkMagic: 42
[db-sync-node.db-sync:Debug:6] [2022-02-02 13:49:09.36 UTC] SELECT "block"."id"
FROM "block"
WHERE "block"."hash" = ?
; [PersistByteString "]\254\ENQ\139\133Q\SUB\254^\150\&6\250\DEL\162\149\163!\196\158\229W@\152\t\SI\242\133|\245\230\203c"]
[db-sync-node:Info:6] [2022-02-02 13:49:09.36 UTC] Inserting Byron Genesis distribution
[db-sync-node.db-sync:Debug:6] [2022-02-02 13:49:09.36 UTC] SELECT COUNT(*)
FROM "block"
; []
[db-sync-node.db-sync:Debug:6] [2022-02-02 13:49:09.36 UTC] INSERT INTO meta ("start_time", "network_name", "version") VALUES (?, ?, ?) ON CONFLICT ON CONSTRAINT unique_meta DO UPDATE SET "start_time" = EXCLUDED."start_time" RETURNING id ;; [PersistUTCTime 2022-02-01 23:43:36 UTC,PersistText "privatenet",PersistText "Version {versionBranch = [12,0,0], versionTags = []}"]
[db-sync-node.db-sync:Debug:6] [2022-02-02 13:49:09.36 UTC] INSERT INTO slot_leader ("hash", "pool_hash_id", "description") VALUES (?, ?, ?) ON CONFLICT ON CONSTRAINT unique_slot_leader DO UPDATE SET "hash" = EXCLUDED."hash" RETURNING id ;; [PersistByteString "]\254\ENQ\139\133Q\SUB\254^\150\&6\250\DEL\162\149\163!\196\158\229W@\152\t\SI\242\133|",PersistNull,PersistText "Genesis slot leader"]
[db-sync-node.db-sync:Debug:6] [2022-02-02 13:49:09.36 UTC] INSERT INTO "block"("hash","epoch_no","slot_no","epoch_slot_no","block_no","previous_id","slot_leader_id","size","time","tx_count","proto_major","proto_minor","vrf_key","op_cert","op_cert_counter") VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) RETURNING "id"; [PersistByteString "]\254\ENQ\139\133Q\SUB\254^\150\&6\250\DEL\162\149\163!\196\158\229W@\152\t\SI\242\133|\245\230\203c",PersistNull,PersistNull,PersistNull,PersistNull,PersistNull,PersistInt64 1,PersistInt64 0,PersistUTCTime 2022-02-01 23:43:36 UTC,PersistInt64 2,PersistInt64 0,PersistInt64 0,PersistNull,PersistNull,PersistNull]
[db-sync-node.db-sync:Debug:6] [2022-02-02 13:49:09.36 UTC] INSERT INTO "tx"("hash","block_id","block_index","out_sum","fee","deposit","size","invalid_before","invalid_hereafter","valid_contract","script_size") VALUES(?,?,?,?,?,?,?,?,?,?,?) RETURNING "id"; [PersistByteString "\200\170\198\230\171~Zk\DC2\226\180\158\247n\178:\US\155\234\181V\155\163\198\FS\229\162\185\248\DC1/\151",PersistInt64 1,PersistInt64 0,PersistText "503000000",PersistText "0",PersistInt64 0,PersistInt64 0,PersistNull,PersistNull,PersistBool True,PersistInt64 0]
[db-sync-node.db-sync:Debug:6] [2022-02-02 13:49:09.36 UTC] INSERT INTO "tx_out"("tx_id","index","address","address_raw","address_has_script","payment_cred","stake_address_id","value","data_hash") VALUES(?,?,?,?,?,?,?,?,?) RETURNING "id"; [PersistInt64 1,PersistInt64 0,PersistText "2657WMsDfac5e1VB4yBWoCXxBVvED7Yd1Yy2MbqbFecptEsiS1huUb6kg9jNU5izo",PersistByteString "\130\216\CANX%\131X\FS>n\176\248\236\236\184\rL\b\193\&4\rr\227\152&Ih\179\213\142\233\175Z\194\137\233\161\STXB\CAN*\NUL\SUB\201\&8\n\204",PersistBool False,PersistNull,PersistNull,PersistText "503000000",PersistNull]
[db-sync-node.db-sync:Debug:6] [2022-02-02 13:49:09.36 UTC] INSERT INTO "tx"("hash","block_id","block_index","out_sum","fee","deposit","size","invalid_before","invalid_hereafter","valid_contract","script_size") VALUES(?,?,?,?,?,?,?,?,?,?,?) RETURNING "id"; [PersistByteString "\185\171\131[t\210\201k\236>2\t\219\204\ETX\170\218bi\191w\219o\143\182\DC3S,M\172\145Q",PersistInt64 1,PersistInt64 0,PersistText "503000000",PersistText "0",PersistInt64 0,PersistInt64 0,PersistNull,PersistNull,PersistBool True,PersistInt64 0]
[db-sync-node.db-sync:Debug:6] [2022-02-02 13:49:09.36 UTC] INSERT INTO "tx_out"("tx_id","index","address","address_raw","address_has_script","payment_cred","stake_address_id","value","data_hash") VALUES(?,?,?,?,?,?,?,?,?) RETURNING "id"; [PersistInt64 2,PersistInt64 0,PersistText "2657WMsDfac72SVer6mTMq5GCoFHAKPSvVE89ZoV18HgfiiDRkpJa74YgcMrJbnW5",PersistByteString "\130\216\CANX%\131X\FS\185\158O\168\194P~\200^\136\230\&5\\sU\SO\244/Tf\f\EMO\vh4\187\233\161\STXB\CAN*\NUL\SUBV\183\182j",PersistBool False,PersistNull,PersistNull,PersistText "503000000",PersistNull]
[db-sync-node:Info:6] [2022-02-02 13:49:09.36 UTC] Initial genesis distribution populated. Hash 5dfe058b85511afe5e9636fa7fa295a321c49ee5574098090ff2857cf5e6cb63
[db-sync-node.db-sync:Debug:6] [2022-02-02 13:49:09.36 UTC] SELECT SUM("tx_out"."value")
FROM "tx_out"
WHERE NOT EXISTS (SELECT ?
FROM "tx_in"
WHERE ("tx_out"."tx_id" = "tx_in"."tx_out_id") AND ("tx_out"."index" = "tx_in"."tx_out_index")
)
; [PersistBool True]
[db-sync-node:Info:6] [2022-02-02 13:49:09.36 UTC] Total genesis supply of Ada: 1006.000000
Node configs that don't[db-sync-node:Error:6] [2022-02-02 13:49:09.37 UTC] Node configs that don't fork to Shelley directly and initiate funds or stakes in Shelley Genesis are not supported.
 fork to Shelley directly and initiate funds or stakes in Shelley Genesis are not supported.
```

I've also tried getting the latest cardano [configs](https://hydra.iohk.io/build/12179730/download/1/index.html) but its a mismatch:
```
Failed reading Byron genesis file "private-testnet/./byron/genesis.json": GenesisHashMismatch (GenesisHash {unGenesisHash = 96fceff972c2c06bd3bb5243c39215333be6d56aaf4823073dca31afe5038471}) 5dfe058b85511afe5e9636fa7fa295a321c49ee5574098090ff2857cf5e6cb63
```

Please advise.

**Comment by woofpool** [comment]
It looks like this commit is doing some additional validation, which is causing the sync to error out.
https://github.com/input-output-hk/cardano-db-sync/commit/6b46441064315677e525c73279fe910939e55b66

I'm not sure how to interpret the error yet.  I'll have to give it a study and update things later.

Yeah, the warning about permissions and what you did to fix the perms is a good addition.  I did that myself just to get rid of the warning, but it's actually harmless as I recall.

In the meantime, I suppose one could check out a commit of `cardano-db-sync` that predates this change on 10/19/21.  
Also, if you skip the db-sync parts of the guide, you can still use the private testnet for submitting transactions.  I will need to dig into the meaning of the error above to fix properly.

**Comment by hududed** [comment]
I see thanks for that, I skipped step 4 and tried submitting the tx, but somehow the balance was not updating:
```
hud@hud-PS63:~/src/cardano-private-testnet-setup$ cardano-cli transaction submit --tx-file tx.signed --testnet-magic 42
Transaction successfully submitted.

hud@hud-PS63:~/src/cardano-private-testnet-setup$ cardano-cli query utxo --address $(cat ${ROOT}/addresses/user1.addr) --testnet-magic 42
                           TxHash                                 TxIx        Amount
--------------------------------------------------------------------------------------
29ab9d52f4afb179bb761dee7dd32acea804905c3f681f49f0fa213b5dbbe399     0        500000000 lovelace + TxOutDatumNone
29ab9d52f4afb179bb761dee7dd32acea804905c3f681f49f0fa213b5dbbe399     1        500000000 lovelace + TxOutDatumNone
```

I did however run that with the wrong (latest) byron, shelley, alonzo config files - could this be the culprit?

**Comment by woofpool** [comment]
Hmmm... possibly.  You may want to re-do the bootstrapping of the network and just use the byron-node-config template file checked into the project.  

I was just looking at the cardano-node project, and I see there is a new script to bootstrap to shelley era from scratch (https://github.com/input-output-hk/cardano-node/blob/master/scripts/shelley-from-scratch/mkfiles.sh) .  Maybe this will fix the cardano-db-sync issue you encountered.  To make that script work with my guide, I'd need to tweak a couple of things, since my guide allows some customization of the variables in the mkfiles script. I will try to get to that this weekend.

**Comment by hududed** [comment]
sounds good. I re-did the bootstrapping, the tx still did not update - I'll try again after this weekend

**Comment by woofpool** [comment]
Hi hududed, 
I was able to duplicate the issue you ran into trying to attach `cardano-db-sync` process.  I logged an issue with the IOG team: https://github.com/input-output-hk/cardano-db-sync/issues/1046

I also modified the guide instructions that includes a transaction to send ADA from user1 to user2.  Instead of using the transaction build-raw, I used the transaction build instead. I successfully transferred funds in my test.  I don't really know why it no longer works with build-raw.  It used to work just fine.

In addition, I updated some node config files based on the latest master branch of `cardano-node`.  They have added some additional alonzo config parameters.

Please let me know, if this fixes things for you (except for the db-sync of course). Also, I really appreciate your going through the guide to discover the issues!

**Comment by hududed** [comment]
Hi woofpool

Thanks hopefully they resolve it quick. However I am still unable to send tx from user1 to user2 - same issue, tx submitted but the amounts were not updated. Which GHC and cabal are you using?

**Comment by woofpool** [comment]
Hi,
I want to make sure you are following the updated guide instructions for sending ADA from user1 to user2.  In the instructions, I don't use build-raw any more; I'm using the alonzo-era build command instead.  That worked for me when I did a fresh test of the guide yesterday.

Also, instead of building them, you may want to download the `cardano-cli` and `cardano-node` executable from IOG and then move them into your $HOME/.local/bin directory.  I was building my executables because I needed `cardano-db-sync`, which I couldn't find as a pre-built binary from IOG, so that was my excuse for building all the binaries.  I am using cabal 3.4.0.0 and GHC 8.10.7.

Other troubleshooting ideas: 

- double check that you are using the correct binaries by doing `which cardano-cli` and `which cardano-node` to verify the path to the executable.
- make sure you've exported CARDANO_NODE_SOCKET_PATH to point at one of the private-testnet BP nodes (e.g. export CARDANO_NODE_SOCKET_PATH=private-testnet/node-bft1/node.sock) in your terminal session where you issue the CLI commands.

**Comment by hududed** [comment]
Ok I reinstalled the executables from [here](https://developers.cardano.org/docs/get-started/installing-cardano-node/#linux) and it works!

**Comment by woofpool** [comment]
> Ok I reinstalled the executables from [here](https://developers.cardano.org/docs/get-started/installing-cardano-node/#linux) and it works!

This is really great news!

**Comment by hududed** [comment]
hi woofpool, following the [issue](https://github.com/input-output-hk/cardano-db-sync/issues/1046) you raised, seems like you have a workaround to setting up database?

**Comment by woofpool** [comment]
> hi woofpool, following the [issue](https://github.com/input-output-hk/cardano-db-sync/issues/1046) you raised, seems like you have a workaround to setting up database?

Hi @hududed , yep, here's what I needed to do.  I will put this into the guide at some point as well.
```
# checkout the latest release (currently 12.0.2) of db-sync
git checkout $(curl -s https://api.github.com/repos/input-output-hk/cardano-db-sync/releases/latest | jq -r .tag_name)

# cherry pick the following 2 commits (using -n to avoid auto committing into local git repo)

# grabs change to Genesis.hs
git cherry-pick -n bff6e182cf41f6f7a9ff3d08bb1fc9984e2d0f66

# grabs change to Block.hs
git cherry-pick -n 132f569bcd297ce73bca407a52acee513aa75389

# build cardano-db-sync executable using `cabal build all` etc.
# copy the executable into your $HOME/.local/bin directory
```
Reset the database in Postgres 
```
# log in to pgsql as root.  You could also login with another account that has superuser privs, too
sudo -u postgres psql

# drop and create the database to reset
drop database privatenet;
create database privatenet;

# list the databases to make sure privatenet exists
\l 
# quit
\q
```
Attach `cardano-db-sync to the network
```
# assume you have network running (you can bootstrap directly to Alonzo, so it won't take but a minute)

# set ROOT variable
ROOT=private-network

# run script to attach db-sync
./scripts/db-sync-start.sh

# it should go into a steady-state of inserting new blocks
```

**Comment by hududed** [comment]
Great!
Okay I did a fresh clone and install and got to this point:
```
➜ cardano-cli query tip --testnet-magic 42 | jq '.era'
"Alonzo"

➜ cardano-cli query protocol-parameters --testnet-magic 42 | jq '.protocolVersion.major'
5

➜ cardano-cli query utxo --address $(cat private-testnet/addresses/user1.addr) --testnet-magic 42
                           TxHash                                 TxIx        Amount
--------------------------------------------------------------------------------------

```
Is this expected?

**Comment by woofpool** [comment]
Hey, 
It appears a recent check-in is preventing the update script from running, which is why user1.addr is not showing any UTxOs.  I created a branch that reverts this check-in and corresponding PR.
In the meantime, can you grab this branch, https://github.com/woofpool/cardano-private-testnet-setup/tree/kurt/revert-35371b10373ab23646cd149024f1016c73be3c37 and repeat the automate script.  You should see that user1.addr has value then.

**Comment by grzegorznowak** [comment]
Thanks for handling this. That PR introduced 2 issues that resulted in my local tests seemingly working indeed.
Now I'm doing it the correct way ultimately, which is by adding a CI automation into the system, along with the actual fix to the problem. 

Should arrive shortly.

**Comment by grzegorznowak** [comment]
fixed with https://github.com/woofpool/cardano-private-testnet-setup/pull/12

**Comment by woofpool** [comment]
@hududed , I verified main is working as expected and 2 UTxOs are not found for user1.addr
